[0m00:39:51.544413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BE75FFE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BE75FF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BE75F290>]}


============================== 00:39:51.564879 | aa075bd6-fcf5-47d6-a087-b85f9d300692 ==============================
[0m00:39:51.564879 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:39:51.565489 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:40:54.027860 [debug] [MainThread]: Starter project path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m00:40:54.072826 [info ] [MainThread]: 
Your new dbt project "real_estate_project_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:40:54.073841 [info ] [MainThread]: Setting up your profile.
[0m00:41:11.631656 [error] [MainThread]: Encountered an error:
list index out of range
[0m00:41:11.677483 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 111, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

[0m00:41:11.678294 [debug] [MainThread]: Command `dbt init` failed at 00:41:11.678294 after 80.33 seconds
[0m00:41:11.679338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BDE1C170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BE427410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2BE12FEF0>]}
[0m00:41:11.679338 [debug] [MainThread]: Flushing usage events
[0m00:41:12.871393 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:41:20.774767 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170C11DD60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F48D040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F48D130>]}


============================== 00:41:20.790398 | e043fea2-d514-440b-91ef-bb7c96dcbfe8 ==============================
[0m00:41:20.790398 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:41:20.790398 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:41:23.301388 [info ] [MainThread]: A project called real_estate_project_dbt already exists here.
[0m00:41:23.301388 [debug] [MainThread]: Command `dbt init` succeeded at 00:41:23.301388 after 2.68 seconds
[0m00:41:23.301388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170ECB54C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170EF7CBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F50ADE0>]}
[0m00:41:23.301388 [debug] [MainThread]: Flushing usage events
[0m00:41:24.455823 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:41:30.850801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835157E390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028351C43FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028351680F20>]}


============================== 00:41:30.851436 | 640a6eb4-e5dd-4b38-975c-ab3801eadd68 ==============================
[0m00:41:30.851436 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:41:30.851436 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:41:36.088973 [info ] [MainThread]: A project called real_estate_project_dbt already exists here.
[0m00:41:36.088973 [debug] [MainThread]: Command `dbt init` succeeded at 00:41:36.088973 after 5.40 seconds
[0m00:41:36.088973 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000283518C1A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028351C43FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002835157E390>]}
[0m00:41:36.088973 [debug] [MainThread]: Flushing usage events
[0m00:41:37.183281 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:41:56.553316 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F64A110D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F64A10E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F64A10E00>]}


============================== 00:41:56.553316 | 1fa00f21-5745-44a9-b4ce-b3c49de8700e ==============================
[0m00:41:56.553316 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:41:56.553316 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init real_estate_project_dbt', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:41:56.576935 [info ] [MainThread]: A project called real_estate_project_dbt already exists here.
[0m00:41:56.576935 [debug] [MainThread]: Command `dbt init` succeeded at 00:41:56.576935 after 0.18 seconds
[0m00:41:56.576935 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6453A030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6448CBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F646F09B0>]}
[0m00:41:56.576935 [debug] [MainThread]: Flushing usage events
[0m00:41:57.774461 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:42:16.988573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1CF42C5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1CF1E2F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1CFAA14F0>]}


============================== 00:42:16.988573 | c7a04518-aed2-47e4-8d1b-f554e8e5b7f3 ==============================
[0m00:42:16.988573 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:42:16.988573 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init real_estate_project_dbt', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:42:17.026538 [debug] [MainThread]: Starter project path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m00:42:17.035361 [info ] [MainThread]: 
Your new dbt project "real_estate_project_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:42:17.035361 [info ] [MainThread]: Setting up your profile.
[0m00:44:28.247447 [info ] [MainThread]: Profile real_estate_project_dbt written to C:\Users\nikhi\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:44:28.247447 [debug] [MainThread]: Command `dbt init` succeeded at 00:44:28.247447 after 131.42 seconds
[0m00:44:28.247447 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1CF42DCD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1CFAF1E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E1A5E480>]}
[0m00:44:28.247447 [debug] [MainThread]: Flushing usage events
[0m00:44:29.539529 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:44:41.980721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026148CE0170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026148C5B6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026148BB5D00>]}


============================== 00:44:41.985721 | 439b92ad-d273-4fea-9b08-394a3ada9b98 ==============================
[0m00:44:41.985721 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:44:41.987401 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:44:42.030579 [info ] [MainThread]: dbt version: 1.10.1
[0m00:44:42.030579 [info ] [MainThread]: python version: 3.12.2
[0m00:44:42.030579 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:44:42.030579 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:44:43.011893 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:44:43.011893 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:44:43.011893 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:44:43.011893 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:44:43.011893 [debug] [MainThread]: Command `dbt debug` failed at 00:44:43.011893 after 1.26 seconds
[0m00:44:43.011893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026148CE0170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026158D2DB20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000261490997F0>]}
[0m00:44:43.011893 [debug] [MainThread]: Flushing usage events
[0m00:44:44.101050 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:46:35.102678 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F6A0C5F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F8FF0170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F8FAE3C0>]}


============================== 00:46:35.102678 | aa253dce-50e2-49d4-87b0-f7fd31659123 ==============================
[0m00:46:35.102678 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:46:35.102678 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:46:35.134175 [info ] [MainThread]: dbt version: 1.10.1
[0m00:46:35.134175 [info ] [MainThread]: python version: 3.12.2
[0m00:46:35.134175 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:46:35.134175 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:46:36.087146 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:46:36.087146 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:46:36.087146 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:46:36.087146 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:46:36.087146 [debug] [MainThread]: Command `dbt debug` failed at 00:46:36.087146 after 1.18 seconds
[0m00:46:36.087146 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F92BB6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002768B706DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002768B7C89B0>]}
[0m00:46:36.087146 [debug] [MainThread]: Flushing usage events
[0m00:46:37.308754 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:50:07.151602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAB759D550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BABA3EE480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BABA3ED5B0>]}


============================== 00:50:07.151602 | 38c17acf-e426-4539-84b6-cd1e919c2e07 ==============================
[0m00:50:07.151602 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:50:07.151602 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m00:50:07.182803 [info ] [MainThread]: dbt version: 1.10.1
[0m00:50:07.182803 [info ] [MainThread]: python version: 3.12.2
[0m00:50:07.182803 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:50:07.182803 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:50:08.166686 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:50:08.166686 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:50:08.166686 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:50:08.166686 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:50:08.170390 [debug] [MainThread]: Command `dbt debug` failed at 00:50:08.170390 after 1.23 seconds
[0m00:50:08.170390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BACB8669F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BACC9D0D40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BACCB68230>]}
[0m00:50:08.170390 [debug] [MainThread]: Flushing usage events
[0m00:50:09.502437 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:50:20.650901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1398DBAA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D13C333EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D13C331220>]}


============================== 00:50:20.653043 | c82b8f5e-5014-48a0-b22d-2b1bb6c9716d ==============================
[0m00:50:20.653043 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:50:20.653043 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:50:20.676958 [info ] [MainThread]: dbt version: 1.10.1
[0m00:50:20.676958 [info ] [MainThread]: python version: 3.12.2
[0m00:50:20.676958 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:50:20.676958 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:50:21.608523 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:50:21.608523 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:50:21.608523 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:50:21.608523 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:50:21.608523 [debug] [MainThread]: Command `dbt debug` failed at 00:50:21.608523 after 1.13 seconds
[0m00:50:21.608523 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D13C16C920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D14D4142F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D14EB08C80>]}
[0m00:50:21.608523 [debug] [MainThread]: Flushing usage events
[0m00:50:22.781772 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:50:57.762613 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D7617F1580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D762033A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D761311B50>]}


============================== 00:50:57.772817 | 9fc7d696-013d-4a54-9ceb-1d25948e9c3c ==============================
[0m00:50:57.772817 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:50:57.772817 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:50:57.797957 [info ] [MainThread]: dbt version: 1.10.1
[0m00:50:57.797957 [info ] [MainThread]: python version: 3.12.2
[0m00:50:57.798957 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:50:57.798957 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:50:58.747009 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:50:58.747009 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:50:58.747009 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:50:58.747009 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:50:58.747009 [debug] [MainThread]: Command `dbt debug` failed at 00:50:58.747009 after 1.14 seconds
[0m00:50:58.747009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D761A608F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D772AA8860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D772BBB0B0>]}
[0m00:50:58.747009 [debug] [MainThread]: Flushing usage events
[0m00:50:59.867325 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:51:21.226079 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002076E603AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207714EE990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207714EFE30>]}


============================== 00:51:21.237248 | ad9b7b27-8911-4e5c-8fba-8cd7b323cb15 ==============================
[0m00:51:21.237248 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:51:21.239210 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug --config-dir', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:51:21.261332 [info ] [MainThread]: To view your profiles.yml file, run:

start C:\Users\nikhi\.dbt
[0m00:51:21.261332 [debug] [MainThread]: Command `dbt debug` succeeded at 00:51:21.261332 after 0.17 seconds
[0m00:51:21.261332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020771318CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002077138CE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020771843E90>]}
[0m00:51:21.261332 [debug] [MainThread]: Flushing usage events
[0m00:51:22.437624 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:52:41.835744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002831782C560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028317521F40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002831782C4D0>]}


============================== 00:52:41.835744 | 251c7499-4c9d-4703-941a-59d77617b0e6 ==============================
[0m00:52:41.835744 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:52:41.835744 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:52:41.864180 [info ] [MainThread]: dbt version: 1.10.1
[0m00:52:41.866247 [info ] [MainThread]: python version: 3.12.2
[0m00:52:41.866247 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:52:41.866247 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:52:42.822125 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:52:42.822125 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:52:42.822125 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:52:42.822125 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:52:42.822125 [debug] [MainThread]: Command `dbt debug` failed at 00:52:42.822125 after 1.14 seconds
[0m00:52:42.822125 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000283171F07A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002831713B7A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002832891DBB0>]}
[0m00:52:42.822125 [debug] [MainThread]: Flushing usage events
[0m00:52:44.007241 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:55:24.868092 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB9FFB920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BBC40B530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BBC40B7A0>]}


============================== 00:55:24.868092 | 086692f8-5b46-4c59-83b3-2849f752866b ==============================
[0m00:55:24.868092 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:55:24.868092 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:55:24.894075 [info ] [MainThread]: dbt version: 1.10.1
[0m00:55:24.894075 [info ] [MainThread]: python version: 3.12.2
[0m00:55:24.894075 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:55:24.894075 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:55:25.858930 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:55:25.858930 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:55:25.858930 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:55:25.858930 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:55:25.858930 [debug] [MainThread]: Command `dbt debug` failed at 00:55:25.858930 after 1.21 seconds
[0m00:55:25.858930 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BBC8CC800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BCDE00140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BCC9AD910>]}
[0m00:55:25.858930 [debug] [MainThread]: Flushing usage events
[0m00:55:27.076993 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:55:33.807256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002857B88BB60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002857DF27F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002857DF25DC0>]}


============================== 00:55:33.819049 | 889d3025-6606-407b-be59-ee2f86211a82 ==============================
[0m00:55:33.819049 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:55:33.819049 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:55:33.843127 [info ] [MainThread]: dbt version: 1.10.1
[0m00:55:33.843127 [info ] [MainThread]: python version: 3.12.2
[0m00:55:33.843127 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:55:33.843127 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:55:34.756506 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:55:34.757474 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:55:34.757812 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:55:34.757812 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:55:34.758848 [debug] [MainThread]: Command `dbt debug` failed at 00:55:34.758848 after 1.09 seconds
[0m00:55:34.758848 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002857E55DAF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002857E71C0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002850F4EE270>]}
[0m00:55:34.758848 [debug] [MainThread]: Flushing usage events
[0m00:55:35.874148 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:58:46.476461 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002957F03D550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002957F03D4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002957F03D2B0>]}


============================== 00:58:46.481151 | d96162f4-2e19-447f-8e9f-e39c5a22fe4b ==============================
[0m00:58:46.481151 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:58:46.482152 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:58:46.493263 [info ] [MainThread]: dbt version: 1.10.1
[0m00:58:46.493263 [info ] [MainThread]: python version: 3.12.2
[0m00:58:46.493263 [info ] [MainThread]: python path: C:\Users\nikhi\AppData\Local\Programs\Python\Python312\python.exe
[0m00:58:46.493263 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m00:58:47.493473 [info ] [MainThread]: Using profiles dir at C:\Users\nikhi\.dbt
[0m00:58:47.493473 [info ] [MainThread]: Using profiles.yml file at C:\Users\nikhi\.dbt\profiles.yml
[0m00:58:47.494577 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
[0m00:58:47.494577 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:58:47.495613 [debug] [MainThread]: Command `dbt debug` failed at 00:58:47.495613 after 1.23 seconds
[0m00:58:47.496614 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002957F03CD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002950FE64BC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002950F410860>]}
[0m00:58:47.496614 [debug] [MainThread]: Flushing usage events
[0m00:58:48.651904 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:07:46.462449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9ED610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9ED340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9ED2B0>]}


============================== 01:07:46.467762 | 5a63d90c-e70a-44ea-bb4b-d158f79749b2 ==============================
[0m01:07:46.467762 [info ] [MainThread]: Running with dbt=1.10.1
[0m01:07:46.468761 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:07:46.469769 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:07:46.469769 [debug] [MainThread]: Command `dbt run` failed at 01:07:46.469769 after 0.17 seconds
[0m01:07:46.469769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9ECAA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9EFA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157BA9ED040>]}
[0m01:07:46.469769 [debug] [MainThread]: Flushing usage events
[0m01:07:47.749975 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:26:36.441577 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A109ECC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A10148C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A109CE30>]}


============================== 00:26:36.447765 | 702a9b7e-7337-44e1-b2b8-812b85dfe00e ==============================
[0m00:26:36.447765 [info ] [MainThread]: Running with dbt=1.10.1
[0m00:26:36.448743 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:26:36.448743 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:26:36.450768 [debug] [MainThread]: Command `dbt run` failed at 00:26:36.449768 after 0.23 seconds
[0m00:26:36.450768 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A07009B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A0E40BC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188A107FE30>]}
[0m00:26:36.450768 [debug] [MainThread]: Flushing usage events
[0m00:26:37.838306 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:50:35.721457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234ECD96900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234ECB307D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234EC6F95E0>]}


============================== 23:50:35.739534 | 269f11c1-a9ea-49d6-bc4e-0dcd645580d2 ==============================
[0m23:50:35.739534 [info ] [MainThread]: Running with dbt=1.10.1
[0m23:50:35.743900 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nikhi\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m23:50:35.745066 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\nikhi\Desktop\real-estate-data-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:50:35.749276 [debug] [MainThread]: Command `dbt run` failed at 23:50:35.749276 after 0.36 seconds
[0m23:50:35.749276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234ECA9ECC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234ECB307D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234ECD96900>]}
[0m23:50:35.753334 [debug] [MainThread]: Flushing usage events
[0m23:50:37.303823 [debug] [MainThread]: An error was encountered while trying to flush usage events
